name: api-carros
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ajustando a versão do jdk para 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
      - name: Construindo com Maven
      run: mvn --batch-mode --update-snapshots verify

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  server:
    port: ${PORT:8080}